### ISSUE TITLE
Every request for a municipality returns the same name

### ISSUE THREAD

**Issue by Kentverger** [IcaliaLabs/sepomex#11]
When I request for example: 
`https://sepomex-api.herokuapp.com/api/v1/states/24/municipalities`

Its return: 

```
{

    "municipalities": [
        {
            "id": 106473,
            "name": "San Luis Potosí",
            "municipality_key": "028",
            "zip_code": "78001",
            "state_id": 24
        },
        {
            "id": 106474,
            "name": "San Luis Potosí",
            "municipality_key": "028",
            "zip_code": "78001",
            "state_id": 24
        },
        {
            "id": 106475,
            "name": "San Luis Potosí",
            "municipality_key": "028",
            "zip_code": "78001",
            "state_id": 24
        },
```

Even if I ask for a specific municipality it returns the same:
`https://sepomex-api.herokuapp.com/api/v1/municipalities/106473`
`https://sepomex-api.herokuapp.com/api/v1/municipalities/106474`

**Comment by kurenn** [comment]
Seems to be right, let me check for details, should not be happening, thanks for reporting this!

**Comment by Kentverger** [comment]
Thank you any news form this issue?

**Comment by kurenn** [comment]
I'm still diggin, I think is an issue from the CSV from sepomex

**Comment by kurenn** [comment]
It is now fixed! I'm closing this
