### ISSUE TITLE
Some Postal Codes returning nothing

### ISSUE THREAD

**Issue by rogomezh** [IcaliaLabs/sepomex#13]
I found that some CPs are returning nothing as result

for example  11570

in the sepomex info it returns values, and csv also do have info

**Comment by kurenn** [comment]
Did you take a look into the CSV to verify if this exists?

**Comment by rogomezh** [comment]
Yes,in the CSV effectively does not exist this CP, (among some others),

But when retrieveing the information directly from sepomex them it does.

So bad the info they provide is so inconsistent, but it is the "official one"

**Comment by kurenn** [comment]
That's sad, let me see if I can contact them and let them know! Thanks for reporting this!

**Comment by kurenn** [comment]
I contact the guys from Sepomex, they argue that if they don't have that on the CSV, there should be an error on the address or something, or in the worst case it does not exist, at least for them...
