### ISSUE TITLE
Continuous updating

### ISSUE THREAD

**Issue by Eflores89** [IcaliaLabs/sepomex#14]
Quick question, who is responsible for updating this API? Is it SEPOMEX or Icalia? Is it reasonable to create code linking to this? (meaning will it be updated or maintained as needed?).

thanks!

**Comment by kurenn** [comment]
Yeah, I'm working on a automated task to download each thursday(date on which SEPOMEX updates) and recreate the database. You can use it with confidence!

**Comment by Eflores89** [comment]
thanks! awesome!!
