### ISSUE TITLE
API is not online, discontinued?

### ISSUE THREAD

**Issue by arturoaviles** [IcaliaLabs/sepomex#18]
I tried to call the API but I didn't receive a response.

**Comment by kurenn** [comment]
How did you made the call? are you using this http://sepomex.icalialabs.com/api/v1/zip_codes ?

**Comment by arturoaviles** [comment]
Ok I wrote **curl -X GET http://sepomex.icalialabs.com/api/v1/municipalities/1** and it worked but when I tried **curl -X GET http://sepomex.icalialabs.com/api/v1/zip_codes/52930** it said it couldn't find it

**Comment by arturoaviles** [comment]
I also tried 

> **curl -X GET http://sepomex.icalialabs.com/api/v1/municipalities -d zip_code=67173**

But the answer was 

{"municipalities":[],"meta":{"pagination":{"per_page":50,"total_pages":0,"total_objects":0}}}

**Comment by kurenn** [comment]
Ok, maybe the documentation is not clear enough, but can you please try this:

```bash
curl -X GET http://sepomex.icalialabs.com/api/v1/zip_codes -d zip_code=67173
```

It might be a good idea to make it more REST, so you don't depend on the `zip_code` param, please let me know how it goes!

**Comment by carlosepp** [comment]
Gettig the following response:

```code curl -X GET http://sepomex.icalialabs.com/api/v1/zip_codes -d zip_code=67173
curl: (6) Could not resolve host: sepomex.icalialabs.com
```

Is the api discontinued? is the project deprecated?

**Comment by kurenn** [comment]
Sorry about this, let me lift the server, and let you know! thanks for reporting this!

**Comment by kurenn** [comment]
You can use this `https://sepomex-api.herokuapp.com/` as the base host name while we are back to normal

**Comment by carlosepp** [comment]
thanks @kurenn, will try that

**Comment by kurenn** [comment]
@carlosepp The service is back to normal, you can use `http://sepomex.icalialabs.com` if you want to

**Comment by kurenn** [comment]
@carlosepp were you able to try the service?
