### ISSUE TITLE
Calling City ID 3

### ISSUE THREAD

**Issue by arturoaviles** [IcaliaLabs/sepomex#19]
When calling:

> **curl -X GET http://sepomex.icalialabs.com/api/v1/cities/2**

It returns:

**{"id":2,"name":"Aguascalientes","state_id":2}**

BUT when you call:

> **curl -X GET http://sepomex.icalialabs.com/api/v1/cities/3** 

It returns:

**{"id":3,"name":"","state_id":2}**

**Comment by kurenn** [comment]
It is weird, what are you expecting to have in return?

**Comment by kurenn** [comment]
Let me take a look at this

**Comment by Wikitelmex** [comment]
> When calling:
> 
> > **curl -X GET http://sepomex.icalialabs.com/api/v1/cities/2**
> 
> It returns:
> 
> **{"id":2,"name":"Aguascalientes","state_id":2}**
> 
> BUT when you call:
> 
> > **curl -X GET http://sepomex.icalialabs.com/api/v1/cities/3**
> 
> It returns:
> 
> **{"id":3,"name":"","state_id":2}**

it may be deleted in db, in the next data load it will be fixed
