### ISSUE TITLE
CORS problem

### ISSUE THREAD

**Issue by FreddoCG** [IcaliaLabs/sepomex#36]
Hi!
When I make the request with ajax it does not return a response. in the console it shows the error which is a CORS problem.
The code I use for the request is:

```
var url = "http://sepomex.icalialabs.com/api/v1/zip_codes?zip_code=" + CP;
    $.ajax({
        url : url,
        type: "GET",
        dataType : "JSON",
        async: true,
        cache: false
    })
        .done(function(data,status) {
            console.log(data)
        })
        .fail(function(xhr, status) {
            console.error(xhr);
        });
```

And the error it returns is:
`
Access to XMLHttpRequest at 'http://sepomex.icalialabs.com/api/v1/zip_codes?city=guadalupe&state=nuevo%20leon' from origin 'http://localhost' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

This problem appeared since yesterday (07/28/2020) because before it worked normally.
Sorry for my English

**Comment by kurenn** [comment]
Thanks for reporting this, we can take a look into this, my suggestion in the meantime would be to clone the project and run it locally, so you can keep moving forward
