### ISSUE TITLE
Step 8 error

### ISSUE THREAD

**Issue by experttyce** [IcaliaLabs/sepomex#40]
addgroup: The group `root' already exists.
useradd: group '1000' does not exist
ERROR: Service 'web' failed to build : The command '/bin/sh -c addgroup --gid ${DEVELOPER_GID} ${DEVELOPER_USERNAME}  ; useradd -r -m -u ${DEVELOPER_UID} --gid ${DEVELOPER_GID} -d /code    -c "Developer User,,," ${DEVELOPER_USERNAME}' returned a non-zero code: 6

**Comment by Wikitelmex** [comment]
> addgroup: The group `root' already exists. useradd: group '1000' does not exist ERROR: Service 'web' failed to build : The command '/bin/sh -c addgroup --gid DEVELOPERGID{DEVELOPER_USERNAME} ; useradd -r -m -u DEVELOPERUID−−gid{DEVELOPER_GID} -d /code -c "Developer User,,," ${DEVELOPER_USERNAME}' returned a non-zero code: 6

Hello, that may happen when you are logged in as root, it's supposed that you are logged in as a normal user when you open the project inside a container.
